[package]
name = "lastrs"
version = "0.1.0"
edition = "2024"

[dependencies]
client = "0.1.1-beta1"
colored = "3.0.0"
futures = "0.3.31"
futures-util = "0.3.31"
lastfm = "0.10.0"
reqwest = "0.12.20"
throbber = "0.1.4"
tokio = "1.45.1"
unaccent = "0.1.1"
winconsole = "0.11.1"
